export default {
  BAD_REQUEST: 'AS_BAD_REQUEST',

  UNAUTHORIZED: 'AS_UNAUTHORIZED',

  FORBIDDEN: 'AS_FORBIDDEN',

  NOT_FOUND: 'AS_NOT_FOUND',

  CONFLICT: 'AS_CONFLICT',

  INTERNAL_SERVER_ERROR: 'AS_INTERNAL_SERVER_ERROR',
};
